src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity=Episode::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $episode;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $rate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->author;
    }

    public function setUser(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->episode;
    }

    public function setEpisode(?Episode $episode): self
    {
        $this->episode = $episode;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }
}

templates/includes/_navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Wild Séries</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active d-flex">
                <a class="nav-link" href="{{ path('app_index') }}">Accueil<span class="sr-only">(current)</span></a>
                <a class="nav-link" href="{{ path('program_index') }}">Programmes</a>
            </li>
        </ul>
    </div>

    <div>
        {% if app.user %}
            {{ app.user.email }}
            <a href="{{ path('app_account') }}">Mon compte</a>
            <a href="{{ path('app_logout') }}"> Se déconnecter</a>
        {% else %}
            <a href="{{ path('app_login') }}"> Se connecter</a>
            <a href="{{ path('app_register') }}">S'inscrire</a>
        {% endif %}
    </div>
</nav>